// ============================================================
// WAV 时长预解析脚本（仅开发时运行一次）/ One-shot dev script:
// 生成 client/audio_files.lua，把每条 WAV 的时长(毫秒)写进清单，
// 服务器指挥才能精确安排下一次广播（不再需要客户端手工解析 WAV 头）。
// Generates the manifest with pre-computed durations so the server
// conductor can schedule transmissions precisely.
// 用法 / usage:  node tools/gen_audio_manifest.js
// ============================================================

'use strict';

const fs = require('fs');
const path = require('path');

const AUDIO_DIR = path.join(__dirname, '..', 'html', 'audio');
const OUT_FILE = path.join(__dirname, '..', 'client', 'audio_files.lua');

// 解析 WAV 头取时长（逻辑与原版 WavePlayer/GetDurationMilliseconds 一致）
// Parse the WAV header for duration (same logic as the original parser)
function durationMs(filePath) {
    const fd = fs.openSync(filePath, 'r');
    try {
        const size = fs.fstatSync(fd).size;
        const head = Buffer.alloc(12);
        fs.readSync(fd, head, 0, 12, 0);
        if (head.toString('ascii', 0, 4) !== 'RIFF' || head.toString('ascii', 8, 12) !== 'WAVE') {
            return 4000; // 非 WAV 回退 4s / not a WAV, 4s fallback
        }
        const b4 = Buffer.alloc(4);
        const b2 = Buffer.alloc(2);
        let pos = 12;
        let byteRate = 0;
        let dataSize = 0;
        while (pos + 8 <= size) {
            fs.readSync(fd, b4, 0, 4, pos);
            const id = b4.toString('ascii', 0, 4);
            fs.readSync(fd, b4, 0, 4, pos + 4);
            const chunkSize = b4.readInt32LE(0);
            if (chunkSize < 0 || pos + 8 + chunkSize > size) break; // 损坏块 / corrupt chunk
            const chunkStart = pos + 8;
            if (id === 'fmt ') {
                // 跳过格式码(2)+声道数(2)+采样率(4)，取 byteRate(4) / skip format, channels, rate; read byteRate
                fs.readSync(fd, b4, 0, 4, chunkStart + 8);
                byteRate = b4.readInt32LE(0);
            } else if (id === 'data') {
                dataSize = chunkSize;
                break;
            }
            pos = chunkStart + chunkSize + (chunkSize % 2); // 2 字节对齐 / 2-byte alignment
        }
        if (byteRate > 0 && dataSize > 0) {
            return Math.max(250, Math.floor((dataSize * 1000) / byteRate));
        }
        return 4000;
    } finally {
        fs.closeSync(fd);
    }
}

// 按数字顺序排列 RadioChatter01..219 / numeric sort
const names = fs.readdirSync(AUDIO_DIR).filter((f) => f.toLowerCase().endsWith('.wav'));
names.sort((a, b) => {
    const na = parseInt(a.replace(/\D/g, ''), 10) || 0;
    const nb = parseInt(b.replace(/\D/g, ''), 10) || 0;
    return na - nb;
});

const lines = names.map((name) => {
    const dur = durationMs(path.join(AUDIO_DIR, name));
    return "    { file = 'audio/" + name + "', dur = " + dur + ' },';
});

const content = [
    '-- 音频文件清单（脚本自动生成，含预解析时长）/ Audio manifest (auto-generated, with pre-parsed durations)',
    '-- 由 tools/gen_audio_manifest.js 生成；重新生成: node tools/gen_audio_manifest.js',
    "-- Generated by tools/gen_audio_manifest.js; regenerate with: node tools/gen_audio_manifest.js",
    '-- dur = 时长毫秒，服务器指挥据此精确调度同步广播 / dur = duration in ms used by the server conductor',
    '',
    'AudioFiles = {',
    lines.join('\n'),
    '}',
    '',
].join('\n');

fs.writeFileSync(OUT_FILE, content, 'utf8');
console.log('Wrote ' + names.length + ' entries to ' + OUT_FILE);
